
# Installation Command:
# !git clone https://github.com/Majdawad88/image_capture_py.git

import cv2
import time
import numpy as np

# Try-except block ensures the script only attempts to use PiCamera2 on compatible hardware
# The try block: This is where you put code that is "risky." In your case, importing Picamera2 is risky because that library only exists on a Raspberry Pi.
# The except block: This is the backup plan. If the code inside the try block fails, Python stops looking at the try code and immediately jumps to the except section.
try:

    from picamera2 import Picamera2
except ImportError:
    print("Picamera2 not found. Ensure you are running this on a Raspberry Pi.")

def run_image_capture():
    print("Initializing Pi Camera...")
    # Picamera2 (The Class): This is the blueprint.
    # picam2 (The Object): This is your active too
    # By creating the object (picam2), you gain a "remote control" to call specific actions (methods) defined in the class.
    picam2 = Picamera2()

    # Configure for full sensor resolution to prevent unwanted zooming
    # (1296, 972) is a standard 4:3 aspect ratio for the Pi Camera sensor
    # Variable (config): The container. It "catches" and saves the settings generated by the method so you can use them in the next line of code.
    # Object (picam2): Your "active camera." Only an object can perform actions like creating settings.
    # Method (.create_video_configuration): An action that belongs to the object. Think of it as a specialized function built into the camera tool.
    # Parameter (main={"size": ...}): The input or specific instruction. You are telling the method exactly what resolution you want.
    config = picam2.create_video_configuration(main={"size": (1296, 972)})
    # Object (picam2): Your "active camera" tool.
    # Method (.configure): The action of applying rules. It’s like hitting the "Apply" button in a settings menu.
    # Argument/Parameter (config): The input. This is the variable from the previous line that contains your resolution (1296x972).
    picam2.configure(config)
    print("Starting camera...")
    picam2.start()

    # --- Window Setup ---
    # Setup an OpenCV window with a specific size and screen position
    # What it does: It creates the frame that holds the video.
    # In your picture: Look at the very top of your preview window. You can see the text "Photo Timer"
    window_name = "Photo Timer"
    cv2.namedWindow(window_name, cv2.WINDOW_NORMAL)
    # What it does: It controls how much space the window takes up on your desktop.
    # What it does: It puts the window at a specific "address" on your monitor.
    cv2.moveWindow(window_name, 560, 240)
    cv2.moveWindow(window_name, 500, 200)

    # Initialize timing variables for the countdown
    start_time = time.time()
    countdown_duration = 15

    print(f"Starting {countdown_duration} second countdown...")

    try:
        while True:
            # Capture a single frame as a NumPy array for processing/display
            # picam2 (The Object): Your camera tool.
            # .capture_array() (The Method): The action of grabbing one instant snapshot. It doesn't save a file; it keeps the image in the computer's memory.
            # frame (The Variable): The container that holds the image data.
            frame = picam2.capture_array()

            # Calculate time remaining
            elapsed = time.time() - start_time
            remaining = countdown_duration - int(elapsed)

            if remaining > 0:
                # Setup font for the countdown overlay
                font = cv2.FONT_HERSHEY_SIMPLEX
                text = str(remaining)

                # Draw high-contrast text (Black shadow + Cyan foreground)
                cv2.putText(frame, text, (554, 504), font, 10, (0, 0, 0), 20, cv2.LINE_AA)
                cv2.putText(frame, text, (550, 500), font, 10, (255, 255, 0), 15, cv2.LINE_AA)

                # Display the frame with the countdown text
                cv2.imshow(window_name, frame)

                # Exit loop if the 'q' key is pressed
                if cv2.waitKey(1) & 0xFF == ord('q'):
                    break
            else:
                # Countdown finished: Save the high-resolution image to disk
                print("\nCapturing image...")
                picam2.capture_file("majd.jpg")
                print("Image successfully saved as 'majd.jpg'")
                break
    finally:
        # Release hardware resources and close GUI windows
        picam2.stop()
        cv2.destroyAllWindows()

# Entry point of the script
if __name__ == "__main__":
    run_image_capture()

# To view the image in Linux terminal:
# xdg-open majd.jpg
